apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-nodejs-deployment
  namespace: eks-nodejs-app
  labels:
    app: eks-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-nodejs-app
  template:
    metadata:
      labels:
        app: eks-nodejs-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nodejs-app
        image: 029916934188.dkr.ecr.eu-west-1.amazonaws.com/test:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux