AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - stage
      - production

Globals:
  Function:
    Runtime: java8.al2
    Timeout: 20
    MemorySize: 512
    AutoPublishAlias: !Ref Stage
    Environment:
      Variables:
        TABLE: !Ref BooksTable
        AWS_CODEGURU_PROFILER_GROUP_ARN: !GetAtt CodeGuruProfilerGroup.Arn
        AWS_CODEGURU_PROFILER_ENABLED: true
        AWS_CODEGURU_PROFILER_GROUP_NAME: !Ref CodeGuruProfilerGroup
        AWS_CODEGURU_PROFILER_TARGET_REGION: !Ref "AWS::Region"
        AWS_CODEGURU_PROFILER_HEAP_SUMMARY_ENABLED: true
        JAVA_TOOL_OPTIONS: -javaagent:/opt/codeguru-profiler-java-agent-standalone.jar
    Layers:
      - Ref: MyLayer
      - 'arn:aws:lambda:us-east-1:157417159150:layer:AWSCodeGuruProfilerJavaAgentLayer:5'

Resources:

  # Lambda Layer for the Lambda functions
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda-layer
      CompatibleRuntimes:
        - java8.al2
    Metadata:
      BuildMethod: java8

  # API Gateway resource
  BooksApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "books-api-${Stage}"
      StageName: !Ref Stage
      Variables:
        LAMBDA_ALIAS: !Ref Stage
      TracingEnabled: true

  # DynamoDB table
  BooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: isbn
        Type: String
      SSESpecification:
        SSEEnabled: true

  #Lambda functions

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.home.amazon.serverless.lambda.GetItemHandler::handleRequest
      CodeUri: get-item-service
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "codeguru-profiler:ConfigureAgent"
                - "codeguru-profiler:CreateProfilingGroup"
                - "codeguru-profiler:PostAgentProfile"
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books/{isbn}
            Method: get
            RestApiId:
              Ref: BooksApi
    Metadata:
      BuildMethod: makefile

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.home.amazon.serverless.lambda.PutItemHandler::handleRequest
      CodeUri: put-item-service
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "codeguru-profiler:ConfigureAgent"
                - "codeguru-profiler:CreateProfilingGroup"
                - "codeguru-profiler:PostAgentProfile"
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books
            Method: post
            RestApiId:
              Ref: BooksApi
    Metadata:
      BuildMethod: makefile

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.home.amazon.serverless.lambda.DeleteItemHandler::handleRequest
      CodeUri: delete-item-service
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:DeleteItem
              Resource: {
                "Fn::Sub": [
                    "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}",
                  {
                    "tableName": {
                      "Ref": "BooksTable"
                    }
                  }
                ]
              }
            - Effect: Allow
              Action:
                - "codeguru-profiler:ConfigureAgent"
                - "codeguru-profiler:CreateProfilingGroup"
                - "codeguru-profiler:PostAgentProfile"
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books/{isbn}
            Method: delete
            RestApiId:
              Ref: BooksApi
    Metadata:
      BuildMethod: makefile

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.home.amazon.serverless.lambda.UpdateItemHandler::handleRequest
      CodeUri: update-item-service
      AutoPublishAlias: !Ref Stage
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "codeguru-profiler:ConfigureAgent"
                - "codeguru-profiler:CreateProfilingGroup"
                - "codeguru-profiler:PostAgentProfile"
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books
            Method: put
            RestApiId:
              Ref: BooksApi
    Metadata:
      BuildMethod: makefile

  CodeGuruProfilerGroup:
    Type: AWS::CodeGuruProfiler::ProfilingGroup
    Properties:
      ProfilingGroupName: "AwsSamAppProfilingGroup"
      ComputePlatform: "AWSLambda"


Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${BooksApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/books"