version: 0.2
env:
  variables:
    CI: true
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd react-app
      - npm install --silent
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: react-app/build


