apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ Release.Name }}
  labels:
    app: eks-nodejs-helm-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eks-nodejs-helm-app
  template:
    metadata:
      labels:
        app: eks-nodejs-helm-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nodejs-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      nodeSelector:
        kubernetes.io/os: linux